[tmux]
name = "TMUX"
shortcuts = [ 
  # { name = "Create Window", cmd = ["CTRL+b", "c"] },
  # { name = "Split -", cmd = ["CTRL+b", "\""] },
  # { name = "Split |", cmd = ["CTRL+b", "%"] },
#  { name = "Zen Mode", cmd = ["CTRL+b", "z"] },
  { name = "Close Pane", cmd = ["CTRL+b", "x"] },
  { name = "Copy Mode", cmd = ["CTRL+b", "["] },
#  { name = "Detach", cmd = ["CTRL+b", "d"] },
#  { name = "Attach", cmd = ["CTRL+b", "a"] },
  { name = "Rename Session", cmd = ["CTRL+b", "$"] },
  { name = "Rename Window", cmd = ["CTRL+b", ","] },
  # { name = "List Sessions", cmd = ["CTRL+b", "w"] },
  { name = "Previous Window", cmd = ["CTRL+b", "p"] },
  { name = "Next Window", cmd = ["CTRL+b", "n"] },
  { name = "Move Left", cmd = ["CTRL+b", "{" ] },
  { name = "Move Right", cmd = ["CTRL+b", "}" ] },
  { name = "Transform Pane to Window", cmd = ["CTRL+b", "!" ] },
  { name = "Toggle Layout", cmd = ["CTRL+b", "space" ] },
]

[nvim]
name = "NVIM"
# https://gist.github.com/danidiaz/37a69305e2ed3319bfff9631175c5d0f
# https://gist.github.com/t-mart/610795fcf7998559ea80
shortcuts = [ 
  { name = "Target Directory", cmd = ["m", "t"] },
  { name = "Mark File", cmd = ["m", "f"] },
  { name = "Copy Marked Files", cmd = ["m", "c"] },
  { name = "Move Marked Files", cmd = ["m", "m"] },
  { name = "Execute on Marked Files", cmd = ["m", "x"] },
  { name = "Apply Diff to Marked Files", cmd = ["m", "d"] },
  { name = "Compress/Decompress Marked Files", cmd = ["m", "z"] },
  { name = "Resume Search", cmd = ["<leader>", "s", "r"] },
  { name = "Telescope: Open Split Vertically", cmd = ["CTRL+v"] },
  { name = "Telescope: Open Split Horizontally", cmd = ["CTRL+x"] },
  { name = "Netrw: Go up one directory", cmd = ["-"] },
  { name = "Netrw: Open file horizontally", cmd = ["o"] },
  { name = "Netrw: Open file vertically", cmd = ["v"] },
]

[shell]
name = "Shell"
shortcuts = [ 
  { name = "Delete Word (←)", cmd = ["CTRL+w"] },
  { name = "Delete Word (→)", cmd = ["ESC", "d"] },
  { name = "Move Word (←)", cmd = ["ESC", "b"] },
  { name = "Move Word (→)", cmd = ["ESC", "f"] },
  { name = "Recall last Argument", cmd = ["ESC", "."] },
  { name = "Create a Searchable Set", cmd = ["cat ... | fzf --reverse"] },
]

[lazygit]
name = "LazyGit"
shortcuts = [ 
  { name = "Amend File to Commit (in 3)", cmd = ["shift+A"] },
  { name = "Fixup a Commit with the Current Staging", cmd = ["shift+F"] },
  { name = "Squash all Fixup Commits into this Commit", cmd = ["shift+S"] },
  { name = "Open PR (Browser)", cmd = ["o"] },
  { name = "Revert Commit", cmd = ["t"] },
  { name = "Move Commit Up / Down", cmd = ["ctrl + j / k"] },
]

# [editor]
# name = "IDE"
# shortcuts = [ 
#   { name = "Focus on Chat", cmd = ["Cmd+L"] },
#   { name = "New Chat", cmd = ["Cmd+?"] },
#   { name = "Inline Chat", cmd = ["Cmd+I"] },
# ]

